--- #YAML:1.0
name:                Class-Trigger
version:             0.13
abstract:            ~
license:             ~
author:              ~
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    IO::Scalar:                    0
    Test::More:                    0.32
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
