# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Class-Trigger
version:      0.10_01
version_from: lib/Class/Trigger.pm
installdirs:  site
requires:
    Class::Data::Inheritable:      0.02
    Class::ISA:                    0
    IO::Scalar:                    0
    Test::More:                    0.32

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
